---
url: https://lawrenceypil.com
email: lawrence.ypil@gmail.com

collections:
  pages:
    output: true
    permalink: :name
  posts:
    output: true
    permalink: /selected-works/:slug

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-email-protect
  - jekyll-target-blank

# External link settings (https://github.com/keithmifsud/jekyll-target-blank)
target-blank:
  noreferrer: false

# Sitemap settings
defaults:
  - scope:
      path: "admin/**/*.*"
    values:
      sitemap: false

pagination:
  enabled: true
paginate: 5
paginate_path: "/selected-works/page:num/"

# Library

jquery:
  version: "3.6.0"
  integrity: "sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
